{% set name = "node-graph-widget" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/node_graph_widget-{{ version }}.tar.gz
  sha256: ec4a26ff4965b1e206a3426d6a9ab0b546693acd64e21d503b8d670fdd121cce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >={{ python_min }}
    - anywidget

test:
  imports:
    - node_graph_widget
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Widget for node-graph
  home: https://github.com/scinode/node-graph-widget
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
